name: LinkedIn Auto Poster

on:
  schedule:
    - cron: '0 8 * * *'   # runs every day at 08:00 UTC
  workflow_dispatch:      # allows manual run

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Get post data for today
        id: get_data
        run: |
          python main.py get_data > data.txt
          CONTENT=$(grep "CONTENT_TO_POST::" data.txt | sed 's/CONTENT_TO_POST:://' | tr -d '\n')
          LOCAL_IMAGE_PATH=$(grep "LOCAL_IMAGE_PATH::" data.txt | sed -e 's/^.*LOCAL_IMAGE_PATH::://' | tr -d '\n')
          echo "content=$CONTENT" >> "$GITHUB_OUTPUT"
          echo "local_image_path=$LOCAL_IMAGE_PATH" >> "$GITHUB_OUTPUT"

      - name: Run script to post to LinkedIn
        run: |
          IMAGE_ARG=""
          if [ -n "${{ steps.get_data.outputs.local_image_path }}" ]; then
            IMAGE_ARG="${{ steps.get_data.outputs.local_image_path }}"
          fi
          python main.py post "${{ steps.get_data.outputs.content }}" "$IMAGE_ARG"
        env:
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          LINKEDIN_PERSON_URN: ${{ secrets.LINKEDIN_PERSON_URN }}
